schema_version = 1
extends = ["../../src/Workflows/assets/aircraft/iris_default.toml"]

[px4]
libpath = "../../../../build/px4_sitl_lockstep/src/lib/px4_lockstep/libpx4_lockstep.dylib"
mission_path = "../../src/Workflows/assets/missions/simple_mission.waypoints"

[timeline]
t_end_s = 70.0

[home]
lat_deg = 47.397742
lon_deg = 8.545594
alt_msl_m = 1488.0

[run]
log_csv = "../../../sim_log_alt_1000m.csv"
