name = "PX4Lockstep"
uuid = "05d710f3-cab8-494a-a8a6-ce1ba4a271f6"
version = "0.1.0"

[deps]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Aqua = "0.8"
JET = "0.10"
JuliaFormatter = "2"
Libdl = "1"
LinearAlgebra = "1"
Printf = "1"
Random = "1"
StaticArrays = "1"
julia = "1.12"
